baseurl = "/"
languageCode = "es-cl"
theme = "hello-friend-ng"
title = "marcelino-m"
subtitle = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
name = "Marcelo Muñoz A."

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Mi blog"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]
  
  homeSubtitle = "..."

  [params.logo]
    logoText = "cd ~/home"
    logoHomeLink = "/"

  # Directory name of your blog content (default is `content/posts`)
  #contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "github"
    url  = "https://github.com/marcelino-m"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/marcelino-m"


[menu]
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about"
  [[menu.main]]
    identifier = "post"
    name       = "posts"
    url        = "/posts"

